"""Generate the district seed migration from the exact audited official source."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_SHA256 = 'e145cc41230d8215dfb0a797230a0c9671827c018ba608bfc3086966da4735c8'
TARGET = ROOT / 'supabase/migrations/202609060005_district_reference_seed.sql'


def generate():
    raw = (ROOT / 'data/reference/hk-districts.geojson').read_bytes()
    if hashlib.sha256(raw).hexdigest() != SOURCE_SHA256:
        raise ValueError('District source changed; review provenance before generating a new migration')
    data = json.loads(raw)
    # Standard-conforming SQL literals; the pinned source is data, not SQL.
    def literal(value):
        return "'" + value.replace("'", "''") + "'"

    rows = []
    for feature in sorted(data['features'], key=lambda item: item['properties']['地區號碼']):
        properties = feature['properties']
        geometry = json.dumps(feature['geometry'], separators=(',', ':'), allow_nan=False)
        values = [properties['地區號碼'], properties['District'], properties['地區'], SOURCE_SHA256]
        rows.append('(' + ','.join(literal(value) for value in values)
                    + ',extensions.st_geomfromgeojson(' + literal(geometry) + '))')
    return ('-- Generated by scripts/generate-district-seed.py; do not edit coordinates.\n'
            '-- Source: https://www.had.gov.hk/psi/hong-kong-administrative-boundaries/hksar_18_district_boundary.json\n'
            '-- Source SHA256: ' + SOURCE_SHA256 + '\n'
            'begin;\nset local standard_conforming_strings = on;\n'
            'insert into public.hk_districts(id,name,name_zh,source_sha256,boundary) values\n'
            + ',\n'.join(rows) + ';\nanalyze public.hk_districts;\ncommit;\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify committed seed matches the pinned source without writing.')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit('District seed differs from the pinned source')
        print('District seed matches the pinned official source (18 districts).')
    else:
        TARGET.write_text(expected)
        print(TARGET.relative_to(ROOT))
